name: build patched app
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/upload-artifact@v3
      - uses: actions/download-artifact@v3
      - uses: actions/checkout@v3
      - uses: mon231/apkpatcher@master
        with:
          original-apk: 'x.apk'
          output-apk: 'patched.apk'
          frida-script: 'ssl.js'